package com.asuscomm.yangyinetwork.websocket.channel.domain;

/**
 * Created by jaeyoung on 2017. 5. 7..
 */
public class User {
    String name;
    int stoneType;

    public User() {
    }

    public User(String name) {
        this.name = name;
    }

    public User(int stoneType) {
        this.name = "autogenerated";
        this.stoneType = stoneType;
    }

    public User(String name, int stoneType) {
        this.name = name;
        this.stoneType = stoneType;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getStoneType() {
        return stoneType;
    }

    public void setStoneType(int stoneType) {
        this.stoneType = stoneType;
    }
}
